// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqgbpbEsqbuEIXuDqJOjCE88juw-R7tW0',
    appId: '1:968321072915:web:25112a2853a0174591a4e6',
    messagingSenderId: '968321072915',
    projectId: 'schooltests1',
    authDomain: 'schooltests1.firebaseapp.com',
    storageBucket: 'schooltests1.appspot.com',
    measurementId: 'G-W2XFLXV6W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChYMS1zG_XSMekShx8x22-A6GTkugK2B8',
    appId: '1:968321072915:android:d9cd3c2e89b80c4291a4e6',
    messagingSenderId: '968321072915',
    projectId: 'schooltests1',
    storageBucket: 'schooltests1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0gcTyoYqq4M7Y9Sm_lj6Qw7UgaK2cU1o',
    appId: '1:968321072915:ios:3ce0b8802b3cdd4f91a4e6',
    messagingSenderId: '968321072915',
    projectId: 'schooltests1',
    storageBucket: 'schooltests1.appspot.com',
    iosBundleId: 'com.example.flutterTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0gcTyoYqq4M7Y9Sm_lj6Qw7UgaK2cU1o',
    appId: '1:968321072915:ios:3ce0b8802b3cdd4f91a4e6',
    messagingSenderId: '968321072915',
    projectId: 'schooltests1',
    storageBucket: 'schooltests1.appspot.com',
    iosBundleId: 'com.example.flutterTests',
  );
}
