// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAau24vWPskfQUjCQ-Y0_H6oOdf49e1n_g',
    appId: '1:619253332200:web:97ae7760f4f7452181f15d',
    messagingSenderId: '619253332200',
    projectId: 'schooltests-525a3',
    authDomain: 'schooltests-525a3.firebaseapp.com',
    storageBucket: 'schooltests-525a3.appspot.com',
    measurementId: 'G-XQ3YMET8JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbpUrySRnLZWgiBNrXHGDqcDyOp3wCc5I',
    appId: '1:619253332200:android:8c0deee89ca842bc81f15d',
    messagingSenderId: '619253332200',
    projectId: 'schooltests-525a3',
    storageBucket: 'schooltests-525a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkW3MIcO0TaQnPonkxwb5q7uehYYz2ab4',
    appId: '1:619253332200:ios:d001cbb08507a84381f15d',
    messagingSenderId: '619253332200',
    projectId: 'schooltests-525a3',
    storageBucket: 'schooltests-525a3.appspot.com',
    iosBundleId: 'com.example.flutterTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkW3MIcO0TaQnPonkxwb5q7uehYYz2ab4',
    appId: '1:619253332200:ios:d001cbb08507a84381f15d',
    messagingSenderId: '619253332200',
    projectId: 'schooltests-525a3',
    storageBucket: 'schooltests-525a3.appspot.com',
    iosBundleId: 'com.example.flutterTests',
  );
}


import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);